CREATE TABLE Genre (
    GenreId INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Tag (
    TagId INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Game (
    GameId UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX),
    Price DECIMAL(18,2) NOT NULL,
    ReleaseDate INT NOT NULL
);

CREATE TABLE GameEdition (
    GameEditionId UNIQUEIDENTIFIER PRIMARY KEY,
    GameId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    Price DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (GameId) REFERENCES Game(GameId)
);

CREATE TABLE GameGenre (
    GameId UNIQUEIDENTIFIER NOT NULL,
    GenreId INT NOT NULL,
    PRIMARY KEY (GameId, GenreId),
    FOREIGN KEY (GameId) REFERENCES Game(GameId),
    FOREIGN KEY (GenreId) REFERENCES Genre(GenreId)
);

CREATE TABLE GameTag (
    GameId UNIQUEIDENTIFIER NOT NULL,
    TagId INT NOT NULL,
    PRIMARY KEY (GameId, TagId),
    FOREIGN KEY (GameId) REFERENCES Game(GameId),
    FOREIGN KEY (TagId) REFERENCES Tag(TagId)
);

CREATE TABLE Cart (
    CartId UNIQUEIDENTIFIER PRIMARY KEY,
    UserId NVARCHAR(100) NOT NULL,
    TotalPrice DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL
);

CREATE TABLE CartItem (
    CartItemId INT PRIMARY KEY IDENTITY(1,1),
    CartId UNIQUEIDENTIFIER NOT NULL,
    GameId UNIQUEIDENTIFIER NOT NULL,
    GameEditionId UNIQUEIDENTIFIER,
    Quantity INT NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    GameName NVARCHAR(200) NOT NULL,
    FOREIGN KEY (CartId) REFERENCES Cart(CartId),
    FOREIGN KEY (GameId) REFERENCES Game(GameId),
    FOREIGN KEY (GameEditionId) REFERENCES GameEdition(GameEditionId)
);

CREATE TABLE Library (
    LibraryId INT PRIMARY KEY IDENTITY(1,1),
    UserId NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL
);

CREATE TABLE LibraryGame (
    LibraryId INT NOT NULL,
    GameId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (LibraryId, GameId),
    FOREIGN KEY (LibraryId) REFERENCES Library(LibraryId),
    FOREIGN KEY (GameId) REFERENCES Game(GameId)
);

CREATE TABLE Rating (
    RatingId INT PRIMARY KEY IDENTITY(1,1),
    GameId UNIQUEIDENTIFIER NOT NULL,
    UserId NVARCHAR(100) NOT NULL,
    Rate INT NOT NULL,
    FOREIGN KEY (GameId) REFERENCES Game(GameId)
);
